steps:
  # Step 1: Install pnpm globally
  - name: 'gcr.io/cloud-builders/npm'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Node.js version:"
        node -v
        echo "NPM version:"
        npm -v
        echo "Installing pnpm globally..."
        npm install -g pnpm
        echo "pnpm version:"
        pnpm -v
        echo "Installing dependencies..."
        cd $DIR  # Replace with your project's directory if needed
        pnpm install

  # Step 2: Build the application
  - name: 'gcr.io/cloud-builders/npm'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Building the application..."
        cd $DIR  # Replace with your project's directory if needed
        pnpm run build
        echo "Build completed"

  # Step 3: Deploy the files to Google Cloud Storage
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - 'gsutil'
      - '-m'
      - 'rsync'
      - '-r'
      - '$DIR'  # Deploy the entire project directory or adjust path
      - 'gs://zikvalencia.com/'  # Replace with your bucket name

# Timeout configuration (Optional)
timeout: '1200s'

# Logging configuration (Optional, Cloud Logging only)
options:
  logging: CLOUD_LOGGING_ONLY  # Log to Cloud Logging only
