steps:
  # Step 1: Install pnpm globally and install dependencies
  - name: 'gcr.io/cloud-builders/npm'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Node.js version:"
        node -v
        echo "NPM version:"
        npm -v
        echo "Installing pnpm globally..."
        npm install -g pnpm
        echo "pnpm version:"
        pnpm -v
        echo "Installing dependencies..."
        cd $DIR
        pnpm install  # Make sure dependencies are installed

  # Step 2: Build the application
  - name: 'gcr.io/cloud-builders/npm'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Building the application..."
        cd $DIR  # Navigate to the directory where your project is
        pnpm run build  # This will run the build script in package.json
        echo "Build completed"

  # Step 3: Deploy the files to Google Cloud Storage
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - 'gsutil'
      - '-m'
      - 'rsync'
      - '-r'
      - 'dist/'  # Adjust if your build folder is not 'dist'
      - 'gs://zikvalencia.com/'  # Your GCS bucket

# Timeout configuration (Optional)
timeout: '1200s'

# Logging configuration (Optional, Cloud Logging only)
options:
  logging: CLOUD_LOGGING_ONLY  # Log to Cloud Logging only