steps:
  - name: 'gcr.io/cloud-builders/npm'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Node.js version:"
        node -v
        echo "NPM version:"
        npm -v
        echo "Installing pnpm globally..."
        npm install -g pnpm
        echo "pnpm version:"
        pnpm -v
        echo "Installing dependencies..."
        pnpm install

  - name: 'gcr.io/cloud-builders/npm'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Building the application..."
        pnpm run build
        echo "Build completed"

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - 'gsutil'
      - '-m'
      - 'rsync'
      - '-r'
      - 'gs://zikvalencia.com/'

timeout: '1200s'

# Use Cloud Logging Only
options:
  logging: CLOUD_LOGGING_ONLY
