/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    About: typeof import('./components/landing/About.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    Header: typeof import('./components/landing/Header.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Skills: typeof import('./components/landing/Skills.vue')['default']
    TimeLine: typeof import('./components/landing/TimeLine.vue')['default']
  }
}
